# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
#RATING_FIELD: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'm3l-20m.inter'

# name of features
# vision_feature_file: 'image/vit.npy'
# text_feature_file: 'text/minilm.npy'
user_graph_dict_file: 'user_graph_dict.npy'

field_separator: "\t"
